= checkpointctl(1)
include::footer.adoc[]

== Name

checkpointctl - a tool for advanced analysis of container checkpoints

== Synopsis

*checkpointctl* _COMMAND_ [_OPTION_]...

== Description

*checkpointctl* is a tool for advanced analysis of container checkpoints
created by Podman, CRI-O, and Kubernetes. It allows users to get an overview
of the checkpoint metadata, inspect the run-time state of processes in the
container, and perform in-depth analysis of checkpoint memory.

== Options

*-h, --help*::
  Show help for checkpointctl

*-v, --version*::
  Show version of checkpointctl

== COMMANDS

[cols="1,1"]
|===
|Command |Description

|checkpointctl-completion
|Generate shell completion scripts

|checkpointctl-inspect(1)
|Display low-level information about a container checkpoint

|checkpointctl-memparse(1)
|Analyze container checkpoint memory

|checkpointctl-show(1)
|Show an overview of container checkpoints
|===


== SEE ALSO

checkpointctl-inspect(1), checkpointctl-memparse(1), checkpointctl-show(1)
