name: Run coverage

on: [push, pull_request]

permissions:
  contents: read
  packages: read

jobs:
  coverage:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}/ci:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      options: --privileged
    steps:
      - name: Fix git safe directory
        run: git config --global --add safe.directory /__w/checkpointctl/checkpointctl
      - name: checkout
        uses: actions/checkout@v4
        with:
          # needed for codecov
          fetch-depth: 0
      - name: Run make coverage
        run: make coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true
          file: .coverage/coverage.out
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
